import { createContext, useContext, useState, useEffect } from 'react';

const UIContext = createContext(null);

const translations = {
    en: {
        brand: 'FlowZint',
        tagline: 'Real-time AI-powered Crisis Response Network',
        homeFeed: 'Home Feed',
        requestHelp: 'Request Help',
        activeChats: 'Active Chats',
        alertCenter: 'Alert Center',
        communityFeed: 'Community Feed',
        myProfile: 'My Profile',
        adminHub: 'Admin Hub',
        logout: 'Logout',
        xpPoints: 'XP Points',
        dailyXp: 'Claim Daily XP',
        gpsLoc: 'GPS Location',
        scanning: 'Scanning...',
        adminReset: 'WIPE & RESEED DATABASE',
        welcomeBack: 'Welcome Back',
        browseRequests: 'Browse Nearby Assistance Cards',
        searchPlaceholder: 'Search query keywords (e.g. React, doctor)...',
        noRequests: 'No open matching requests found in this category.',
        respondButton: 'Respond & Accept Help',
        bookmarkSave: 'Save Bookmark',
        bookmarkSaved: 'Saved ⭐',
        durationLabel: 'Duration Expected',
        budgetLabel: 'Budget (Optional)',
        anonymousLabel: 'Post Request anonymously on public feed',
        submitRequest: 'Dispatch Matching Radar Engine',
        titleLabel: 'Request Title / Prompt',
        descLabel: 'Detailed Description',
        categoryLabel: 'Category (AI Overwrite)',
        urgencyLabel: 'Urgency Level',
        topHelpers: 'Top Weekly Helpers',
        activeHelpers: 'Active Seed Volunteers',
        resolvedIncidents: 'Total Incidents Resolved',
        avgSpeed: 'Average Dispatch Speed',
        weekGrowth: 'Community Incident Growth Vectors (Weekly)',
        logResetSuccess: 'Database reset and seeded volunteers successfully.',
        claimSuccess: 'Claimed daily login reward!',
        chatPlaceholder: 'Type a message to coordinate...',
        chatStandby: 'Select an active direct conversation channel to coordinate help.',
        skillsEndorsements: 'Skills & Expertise Endorsements',
        reviewsHeading: 'Incidents Feedback & Reviews',
        editBio: '✏️ Edit Bio & Icon',
        saveDetails: 'Save Details',
        cancel: 'Cancel',
        availability: 'Availability',
        expertise: 'Expertise Level',
        registerAsHelper: 'I am registering as a Skilled Helper to respond to other requests',
        joinFlowzint: 'Join FlowZint 🚀',
        nextStep: 'Next Step',
        back: 'Back',
        signIn: 'Sign In',
        createAccount: 'Create Account',
        avatarLabel: 'Choose Avatar Icon',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        password: 'Password',
        occupation: 'Occupation Status',
        city: 'City',
        state: 'State',
        country: 'Country',
        all: 'All',
        webDev: 'Web Development',
        design: 'Design',
        academics: 'Academics',
        medical: 'Medical',
        volunteering: 'Volunteering',
        bloodDonation: 'Blood Donation',
        careerAdvice: 'Career Advice',
        generalHelp: 'General Help',
        urgencyLow: '🟢 Low Urgency',
        urgencyMedium: '🟡 Medium Urgency',
        urgencyHigh: '🟠 High Urgency',
        urgencyCritical: '🔴 Critical Emergency',
        durationPlaceholder: 'E.g. 1 hour, 3 days',
        budgetPlaceholder: 'E.g. Free, $50',
        noChats: 'No direct matching chat rooms active. Accept requests on feed to begin.',
        noAlerts: 'No new matches or community activities reported.',
        claimDailyXp: 'Claim Daily XP',
        feedRadarStandby: 'Feed Radar Standby',
        postToFeed: 'Post to Feed',
        shareTips: 'Share Tips, Questions, or Knowledge',
        newPostPlaceholder: 'What would you like to share with the nearby skilled community?',
        upvote: 'Upvote',
        comments: 'Comments',
        save: 'Save',
        commentsFeed: 'COMMENTS FEED',
        noComments: 'No comments posted yet. Write the first response!',
        writeCommentPlaceholder: 'Write a comment reply...',
        send: 'Send',
        logoutButton: 'Logout',
        mvpHub: 'MVP Hub',
        pointsXp: 'XP Points',
        editBioBtn: '✏️ Edit Bio & Icon',
        saveDetailsBtn: 'Save Details',
        cancelBtn: 'Cancel',
        incidentsFeedback: 'Incidents Feedback & Reviews',
        noReviews: 'No reviews posted yet. Resolve tickets to gather seeker ratings.',
        reviewedOn: 'Reviewed on',
        socialStats: 'Social Stats Index',
        completedDeliveries: 'Completed Deliveries',
        avgMatchingResponse: 'Avg Matching Response',
        requestAcceptanceRate: 'Request Acceptance Rate',
        communityContributions: 'Community Contributions',
        confirmRateHelp: '⭐ Confirm & Rate Help Completion',
        rateHelperTitle: '⭐ Rate Helper Delivery',
        howWasExperience: 'How was your coordinate experience with',
        selectStarRating: 'Select Star Rating',
        reviewDetailsLabel: 'Review details',
        reviewPlaceholder: 'Describe their speed, helpfulness, and coordination...',
        submitRatingBtn: 'Submit Rating Feedback',
        adminOpsTitle: 'Admin Operations Control Panel',
        securityLogs: 'Security, Safety & Block Actions logs',
        trustProtocol: 'All user flags, reports, blocks, and auto-checks are handled and logged here. Currently running: **FlowZint Trust Protocol 1.2.0**',
        lobbyRadar: 'Lobby Radar Map',
        radarTitle: '📡 Crisis assistance live dispatch vectors',
        radarDesc: 'Visualizing helper coordinates and dispatch trajectories around Delhi region.',
        activeHelpersRadar: 'helpers active inside scanner',
        simulatingRadar: 'Simulating GPS coordinate ping...',
        connectionDetails: 'Connection Details',
        helperSpecialties: 'Helper Specialties:',
        helperRating: 'Helper Rating:',
        estProximity: 'Est. Proximity:',
        kmAway: 'km away',
        cancelRequestBtn: 'Cancel Request',
        simulateAcceptBtn: '⚡ Simulate Helper Acceptance',
        aiTitleSuggestions: 'Title Recommendations:',
        aiClassifiedCategory: 'Classified Category:',
        aiSuggestedSkills: 'Suggested Skills:',
        aiPossibleSolutions: 'Possible Solutions (Pre-match suggestions):',
        aiLoaderText: 'Analyzing...',
        aiSuggestionsHeader: '🤖 FlowZint AI Assistant Suggestions',
        directChats: 'Direct Chats',
        filterUsers: 'Filter users...',
        inboxStandbyTitle: 'FlowZint Inbox standby',
        inboxStandbyDesc: 'Select an active direct conversation channel to coordinate help deliveries.',
        topMatchingHelpers: '🎯 Top Matching Helpers',
        radialExpandedHelpers: '📡 Radial Expanded Helpers',
        safeguardFooter: '🛡️ FlowZint AI Safeguard Online: Backup endpoints and regex location classifiers ready. Build v1.2.',
        workspaceMenu: 'WORKSPACE MENU',
        pinnedMessageLabel: '📌 Pinned Message:',
        noMatchingMessages: 'No matching messages found.',
        noMessagesYet: 'No messages yet. Send a message to coordinate.',
        youLabel: 'You',
        downloadLabel: 'Download',
        recordingVoiceNote: '🎤 Recording voice note simulation...',
        attachFileTitle: 'Attach file / image',
        emojiDrawerTitle: 'Emoji drawer',
        stopVoiceNote: 'Stop and Send Voice Note',
        recordVoiceNote: 'Record Voice Note',
        searchMessagesPlaceholder: 'Search messages...',
        markRead: 'Mark Read'
    },
    hi: {
        brand: 'फ़्लोज़िंट',
        tagline: 'रीयल-टाइम एआई-संचालित संकट प्रतिक्रिया नेटवर्क',
        homeFeed: 'मुख्य फ़ीड',
        requestHelp: 'सहायता माँगें',
        activeChats: 'सक्रिय चैट',
        alertCenter: 'सूचना केंद्र',
        communityFeed: 'सामुदायिक फ़ीड',
        myProfile: 'मेरी प्रोफ़ाइल',
        adminHub: 'प्रशासक हब',
        logout: 'लॉग आउट',
        xpPoints: 'एक्सपी अंक',
        dailyXp: 'दैनिक एक्सपी लें',
        gpsLoc: 'जीपीएस स्थान',
        scanning: 'स्कैनिंग...',
        adminReset: 'डेटाबेस रीसेट करें',
        welcomeBack: 'आपका स्वागत है',
        browseRequests: 'आस-पास के सहायता अनुरोध देखें',
        searchPlaceholder: 'खोज शब्द (जैसे रिएक्ट, डॉक्टर)...',
        noRequests: 'इस श्रेणी में कोई खुला सहायता अनुरोध नहीं मिला।',
        respondButton: 'मदद के लिए स्वीकार करें',
        bookmarkSave: 'सहेजें',
        bookmarkSaved: 'सहेजा गया ⭐',
        durationLabel: 'अपेक्षित अवधि',
        budgetLabel: 'बजट (वैकल्पिक)',
        anonymousLabel: 'अनुरोध को सार्वजनिक फ़ीड पर गुमनाम रूप से पोस्ट करें',
        submitRequest: 'मैचिंग रडार चालू करें',
        titleLabel: 'अनुरोध शीर्षक / संकेत',
        descLabel: 'विस्तृत विवरण',
        categoryLabel: 'श्रेणी (एआई अधिलेखन)',
        urgencyLabel: 'आपातकाल स्तर',
        topHelpers: 'शीर्ष साप्ताहिक सहायक',
        activeHelpers: 'सक्रिय स्वयंसेवक',
        resolvedIncidents: 'कुल हल की गई घटनाएँ',
        avgSpeed: 'औसत प्रतिक्रिया समय',
        weekGrowth: 'साप्ताहिक सहायता विकास दर',
        logResetSuccess: 'डेटाबेस सफलतापूर्वक रीसेट और सीड किया गया।',
        claimSuccess: 'दैनिक लॉगिन इनाम प्राप्त हुआ!',
        chatPlaceholder: 'समन्वय के लिए संदेश लिखें...',
        chatStandby: 'समन्वय करने के लिए किसी सक्रिय चैट का चयन करें।',
        skillsEndorsements: 'कौशल और विशेषज्ञता समर्थन',
        reviewsHeading: 'प्रतिक्रिया और समीक्षाएं',
        editBio: '✏️ बायो और आइकन बदलें',
        saveDetails: 'विवरण सहेजें',
        cancel: 'रद्द करें',
        availability: 'उपलब्धता',
        expertise: 'विशेषज्ञता स्तर',
        registerAsHelper: 'मैं अन्य अनुरोधों का उत्तर देने के लिए एक कुशल सहायक के रूप में पंजीकरण कर रहा हूँ',
        joinFlowzint: 'फ़्लोज़िंट में शामिल हों 🚀',
        nextStep: 'अगला चरण',
        back: 'पीछे',
        signIn: 'लॉग इन करें',
        createAccount: 'खाता बनाएँ',
        avatarLabel: 'अवतार आइकन चुनें',
        fullName: 'पूरा नाम',
        emailAddress: 'ईमेल पता',
        password: 'पासवर्ड',
        occupation: 'व्यवसाय स्थिति',
        city: 'शहर',
        state: 'राज्य',
        country: 'देश',
        all: 'सभी',
        webDev: 'वेब डेवलपमेंट',
        design: 'डिज़ाइन',
        academics: 'शिक्षा',
        medical: 'चिकित्सा',
        volunteering: 'स्वयंसेवा',
        bloodDonation: 'रक्तदान',
        careerAdvice: 'करियर सलाह',
        generalHelp: 'सामान्य सहायता',
        urgencyLow: '🟢 कम प्राथमिकता',
        urgencyMedium: '🟡 मध्यम प्राथमिकता',
        urgencyHigh: '🟠 उच्च प्राथमिकता',
        urgencyCritical: '🔴 गंभीर आपातकाल',
        durationPlaceholder: 'जैसे: 1 घंटा, 3 दिन',
        budgetPlaceholder: 'जैसे: मुफ्त, $50',
        noChats: 'कोई सीधा चैट रूम सक्रिय नहीं है। शुरू करने के लिए फ़ीड पर अनुरोध स्वीकार करें।',
        noAlerts: 'कोई नया मैच या सामुदायिक गतिविधियां नहीं हैं।',
        claimDailyXp: 'दैनिक एक्सपी प्राप्त करें',
        feedRadarStandby: 'फ़ीड रडார்கள் स्टैंडबाय',
        postToFeed: 'फ़ीड पर पोस्ट करें',
        shareTips: 'युक्तियाँ, प्रश्न या ज्ञान साझा करें',
        newPostPlaceholder: 'आप आस-पास के कुशल समुदाय के साथ क्या साझा करना चाहेंगे?',
        upvote: 'अपवोट',
        comments: 'टिप्पणियाँ',
        save: 'सहेजें',
        commentsFeed: 'टिप्पणी फ़ीड',
        noComments: 'अभी तक कोई टिप्पणी पोस्ट नहीं की गई है। पहली प्रतिक्रिया लिखें!',
        writeCommentPlaceholder: 'एक टिप्पणी उत्तर लिखें...',
        send: 'भेजें',
        logoutButton: 'लॉग आउट',
        mvpHub: 'एमवीपी हब',
        pointsXp: 'एक्सपी अंक',
        editBioBtn: '✏️ बायो और आइकन बदलें',
        saveDetailsBtn: 'विवरण सहेजें',
        cancelBtn: 'रद्द करें',
        incidentsFeedback: 'घटनाओं पर प्रतिक्रिया और समीक्षाएं',
        noReviews: 'अभी तक कोई समीक्षा पोस्ट नहीं की गई है। रेटिंग प्राप्त करने के लिए टिकट हल करें।',
        reviewedOn: 'समीक्षा की तारीख',
        socialStats: 'सामाजिक आँकड़े सूचकांक',
        completedDeliveries: 'पूरी की गई सहायता',
        avgMatchingResponse: 'औसत मिलान प्रतिक्रिया समय',
        requestAcceptanceRate: 'अनुरोध स्वीकृति दर',
        communityContributions: 'सामुदायिक योगदान',
        confirmRateHelp: '⭐ सहायता पूर्ण होने की पुष्टि और रेटिंग करें',
        rateHelperTitle: '⭐ सहायक सेवा को रेट करें',
        howWasExperience: 'आपका इनके साथ समन्वय का अनुभव कैसा रहा',
        selectStarRating: 'स्टार रेटिंग चुनें',
        reviewDetailsLabel: 'समीक्षा विवरण',
        reviewPlaceholder: 'उनकी गति, उपयोगिता और समन्वय का वर्णन करें...',
        submitRatingBtn: 'रेटिंग प्रतिक्रिया सबमिट करें',
        adminOpsTitle: 'प्रशासक संचालन नियंत्रण कक्ष',
        securityLogs: 'सुरक्षा, सुरक्षा और ब्लॉक कार्रवाई लॉग',
        trustProtocol: 'सभी उपयोगकर्ता रिपोर्ट, ब्लॉक और ऑटो-चेक यहाँ संभाले जाते हैं। वर्तमान में चल रहा है: **फ़्लोज़िंट ट्रस्ट प्रोटोकॉल 1.2.0**',
        lobbyRadar: 'लॉबी रडार मानचित्र',
        radarTitle: '📡 संकट सहायता लाइव प्रेषण वैक्टर',
        radarDesc: 'दिल्ली क्षेत्र के आसपास सहायक निर्देशांक और प्रेषण प्रक्षेपवक्र का विज़ुअलाइज़ेशन।',
        activeHelpersRadar: 'स्कैनर के अंदर सक्रिय सहायक',
        simulatingRadar: 'जीपीएस स्थान पिंग का अनुकरण...',
        connectionDetails: 'कनेक्शन का विवरण',
        helperSpecialties: 'सहायक की विशेषताएँ:',
        helperRating: 'सहायक रेटिंग:',
        estProximity: 'अनुमानित निकटता:',
        kmAway: 'किमी दूर',
        cancelRequestBtn: 'अनुरोध रद्द करें',
        simulateAcceptBtn: '⚡ सहायक स्वीकृति का अनुकरण करें',
        aiTitleSuggestions: 'शीर्षक सिफारिशें:',
        aiClassifiedCategory: 'वर्गीकृत श्रेणी:',
        aiSuggestedSkills: 'सुझाए गए कौशल:',
        aiPossibleSolutions: 'संभावित समाधान (पूर्व-मिलान सुझाव):',
        aiLoaderText: 'विश्लेषण कर रहा है...',
        aiSuggestionsHeader: '🤖 फ़्लोज़िंट एआई सहायक सुझाव',
        directChats: 'सीधी चैट',
        filterUsers: 'उपयोगकर्ताओं को फ़िल्टर करें...',
        inboxStandbyTitle: 'फ़्लोज़िंट इनबॉक्स स्टैंडबाय',
        inboxStandbyDesc: 'सहायता वितरण का समन्वय करने के लिए एक सक्रिय चैट का चयन करें।',
        topMatchingHelpers: '🎯 शीर्ष मिलान सहायक',
        radialExpandedHelpers: '📡 विस्तारित दायरे के सहायक',
        safeguardFooter: '🛡️ फ़्लोज़िंट एआई सेफ़गार्ड ऑनलाइन: बैकअप एंडपॉइंट्स और रीगेक्स स्थान क्लासिफायर तैयार हैं। बिल्ड v1.2।',
        workspaceMenu: 'कार्यस्थान मेनू',
        pinnedMessageLabel: '📌 पिन किया गया संदेश:',
        noMatchingMessages: 'कोई मेल खाने वाले संदेश नहीं मिले।',
        noMessagesYet: 'अभी तक कोई संदेश नहीं है। समन्वय के लिए एक संदेश भेजें।',
        youLabel: 'आप',
        downloadLabel: 'डाउनलोड',
        recordingVoiceNote: '🎤 वॉयस नोट सिमुलेशन रिकॉर्ड कर रहा है...',
        attachFileTitle: 'फाइल / इमेज अटैच करें',
        emojiDrawerTitle: 'इमोजी ड्रावर',
        stopVoiceNote: 'वॉयस नोट रोकें और भेजें',
        recordVoiceNote: 'वॉयस नोट रिकॉर्ड करें',
        searchMessagesPlaceholder: 'संदेश खोजें...',
        markRead: 'पढ़ा हुआ चिह्नित करें'
    },
    ta: {
        brand: 'ஃப்ளோசிண்ட்',
        tagline: 'நிகழ்நேர AI-இயங்கும் அவசர கால உதவி தளம்',
        homeFeed: 'முகப்பு ஊட்டம்',
        requestHelp: 'உதவி கோருக',
        activeChats: 'செயலில் உள்ள அரட்டைகள்',
        alertCenter: 'அறிவிப்பு மையம்',
        communityFeed: 'சமூக ஊட்டம்',
        myProfile: 'எனது சுயவிவரம்',
        adminHub: 'நிர்வாக மையம்',
        logout: 'வெளியேறு',
        xpPoints: 'எக்ஸ்பி புள்ளிகள்',
        dailyXp: 'தினசரி எக்ஸ்பி பெறு',
        gpsLoc: 'ஜிபிஎஸ் இருப்பிடம்',
        scanning: 'ஸ்கேன் செய்கிறது...',
        adminReset: 'தரவுத்தளத்தை மீட்டமை',
        welcomeBack: 'நல்வரவு',
        browseRequests: 'அருகிலுள்ள உதவி கோரிக்கைகளை உலாவுக',
        searchPlaceholder: 'தேடல் சொற்கள் (எ.கா. ரியாக்ட், மருத்துவர்)...',
        noRequests: 'இந்த பிரிவில் திறந்த உதவி கோரிக்கைகள் எதுவும் இல்லை.',
        respondButton: 'உதவ ஒப்புக்கொள்',
        bookmarkSave: 'சேமிக்க',
        bookmarkSaved: 'சேமிக்கப்பட்டது ⭐',
        durationLabel: 'எதிர்பார்க்கும் காலம்',
        budgetLabel: 'பட்ஜெட் (விருப்பத்தேர்வு)',
        anonymousLabel: 'கோரிக்கையை பொது ஊட்டங்களில் அநாமதேயமாக இடுகையிடவும்',
        submitRequest: 'பொருந்தும் ரேடாரை இயக்கு',
        titleLabel: 'கோரிக்கை தலைப்பு / தூண்டுதல்',
        descLabel: 'விரிவான விளக்கம்',
        categoryLabel: 'வகை (AI திருத்தம்)',
        urgencyLabel: 'அவசர நிலை',
        topHelpers: 'வாராந்திர சிறந்த உதவியாளர்கள்',
        activeHelpers: 'செயலில் உள்ள தன்னார்வலர்கள்',
        resolvedIncidents: 'தீர்க்கப்பட்ட மொத்த கோரிக்கைகள்',
        avgSpeed: 'சராசரி பதிலளிப்பு நேரம்',
        weekGrowth: 'வாராந்திர உதவி வளர்ச்சி வரைபடம்',
        logResetSuccess: 'தரவுத்தளம் வெற்றிகரமாக மீட்டமைக்கப்பட்டது.',
        claimSuccess: 'தினசரி உள்நுழைவு வெகுமதி பெறப்பட்டது!',
        chatPlaceholder: 'உதவி விவரங்களை ஒருங்கிணைக்க செய்தி அனுப்பவும்...',
        chatStandby: 'விவரங்களை ஒருங்கிணைக்க செயலில் உள்ள அரட்டை அறையைத் தேர்ந்தெடுக்கவும்.',
        skillsEndorsements: 'திறன்கள் மற்றும் நிபுணத்துவ அங்கீகாரம்',
        reviewsHeading: 'கருத்துகள் மற்றும் மதிப்புரைகள்',
        editBio: '✏️ சுயவிவரத்தை திருத்துக',
        saveDetails: 'விவரங்களை சேமி',
        cancel: 'ரத்துசெய்',
        availability: 'கிடைக்கும் தன்மை',
        expertise: 'நிபுணத்துவ நிலை',
        registerAsHelper: 'மற்ற கோரிக்கைகளுக்கு பதிலளிக்க நான் ஒரு உதவியாளராக பதிவு செய்கிறேன்',
        joinFlowzint: 'ஃப்ளோசிண்டில் இணைக 🚀',
        nextStep: 'அடுத்த படி',
        back: 'பின்செல்',
        signIn: 'உள்நுழைக',
        createAccount: 'கணக்கை உருவாக்கு',
        avatarLabel: 'அவதார் சின்னத்தைத் தேர்ந்தெடுக்கவும்',
        fullName: 'முழு பெயர்',
        emailAddress: 'மின்னஞ்சல் முகவரி',
        password: 'கடவுச்சொல்',
        occupation: 'தொழில் நிலை',
        city: 'நகரம்',
        state: 'மாநிலம்',
        country: 'நாடு',
        all: 'அனைத்தும்',
        webDev: 'வலை அபிவிருத்தி',
        design: 'வடிவமைப்பு',
        academics: 'கல்வி',
        medical: 'மருத்துவம்',
        volunteering: 'தன்னார்வத் தொண்டு',
        bloodDonation: 'இரத்த தானம்',
        careerAdvice: 'தொழில் வழிகாட்டுதல்',
        generalHelp: 'பொதுவான உதவி',
        urgencyLow: '🟢 குறைந்த அவசரம்',
        urgencyMedium: '🟡 நடுத்தர அவசரம்',
        urgencyHigh: '🟠 அதிக அவசரம்',
        urgencyCritical: '🔴 தீவிர அவசரநிலை',
        durationPlaceholder: 'எ.கா. 1 மணிநேரம், 3 நாட்கள்',
        budgetPlaceholder: 'எ.கா. இலவசம், $50',
        noChats: 'செயலில் உள்ள அரட்டை இல்லை. தொடங்க ஊட்டத்திலிருந்து கோரிக்கைகளை ஏற்கவும்.',
        noAlerts: 'புதிய பொருத்தங்கள் அல்லது சமூக நடவடிக்கைகள் எதுவும் இல்லை.',
        claimDailyXp: 'தினசரி எக்ஸ்பி பெறு',
        feedRadarStandby: 'ஊட்ட ரேடார் காத்திருப்பு',
        postToFeed: 'ஊட்டத்தில் இடுகையிடுக',
        shareTips: 'குறிப்புகள், கேள்விகள் அல்லது அறிவைப் பகிரவும்',
        newPostPlaceholder: 'அருகிலுள்ள திறமையான சமூகத்துடன் நீங்கள் எதைப் பகிர விரும்புகிறீர்கள்?',
        upvote: 'வாக்களிக்கவும்',
        comments: 'கருத்துகள்',
        save: 'சேமி',
        commentsFeed: 'கருத்துகள் ஊட்டம்',
        noComments: 'இதுவரை எந்தக் கருத்தும் இடுகையிடப்படவில்லை. முதல் பதிலை எழுதுங்கள்!',
        writeCommentPlaceholder: 'ஒரு கருத்து பதிலை எழுதுங்கள்...',
        send: 'அனுப்பு',
        logoutButton: 'வெளியேறு',
        mvpHub: 'எம்விபி மையம்',
        pointsXp: 'எக்ஸ்பி புள்ளிகள்',
        editBioBtn: '✏️ சுயவிவரத்தை திருத்துக',
        saveDetailsBtn: 'விவரங்களை சேமி',
        cancelBtn: 'ரத்துசெய்',
        incidentsFeedback: 'நிகழ்வுகள் பற்றிய கருத்துகள் மற்றும் மதிப்புரைகள்',
        noReviews: 'இதுவரை எந்த மதிப்புரைகளும் இடுகையிடப்படவில்லை. மதிப்பீடுகளைப் பெற கோரிக்கைகளைத் தீர்க்கவும்.',
        reviewedOn: 'மதிப்பாய்வு செய்யப்பட்ட நாள்',
        socialStats: 'சமூக புள்ளிவிவரக் குறியீடு',
        completedDeliveries: 'தீர்க்கப்பட்ட கோரிக்கைகள்',
        avgMatchingResponse: 'சராசரி பதில் நேரம்',
        requestAcceptanceRate: 'கோரிக்கை ஏற்பு விகிதம்',
        communityContributions: 'சமூக பங்களிப்புகள்',
        confirmRateHelp: '⭐ உதவி நிறைவை உறுதிசெய்து மதிப்பிடவும்',
        rateHelperTitle: '⭐ உதவியாளர் சேவையை மதிப்பிடவும்',
        howWasExperience: 'உங்களுடன் ஒருங்கிணைந்த அனுபவம் எவ்வாறு இருந்தது',
        selectStarRating: 'நட்சத்திர மதிப்பீட்டைத் தேர்ந்தெடுக்கவும்',
        reviewDetailsLabel: 'மதிப்பாய்வு விவரங்கள்',
        reviewPlaceholder: 'அவர்களின் வேகம், உதவித்தன்மை மற்றும் ஒருங்கிணைப்பை விவரிக்கவும்...',
        submitRatingBtn: 'மதிப்பாய்வைச் சமர்ப்பிக்கவும்',
        adminOpsTitle: 'நிர்வாக செயல்பாட்டுக் கட்டுப்பாட்டு குழு',
        securityLogs: 'பாதுகாப்பு மற்றும் தடுப்பு நடவடிக்கைகள் பதிவுகள்',
        trustProtocol: 'அனைத்து பயனர் புகார்கள், தடுப்புகள் மற்றும் தானியங்கி சோதனைகள் இங்கு கையாளப்பட்டு பதிவு செய்யப்படுகின்றன. தற்போது இயங்குவது: **ஃப்ளோசிண்ட் டிரஸ்ட் புரோட்டோகால் 1.2.0**',
        lobbyRadar: 'ரேடார் வரைபடம்',
        radarTitle: '📡 உதவி கோரிக்கை நிகழ்நேர வரைபடம்',
        radarDesc: 'டெல்லி பகுதியைச் சுற்றியுள்ள உதவியாளர் ஒருங்கிணைப்புகள் மற்றும் திசையன்களைக் காட்சிப்படுத்துதல்.',
        activeHelpersRadar: 'ரேடாரில் உள்ள உதவியாளர்கள்',
        simulatingRadar: 'ஜிபிஎஸ் இருப்பிடத்தை தேடுகிறது...',
        connectionDetails: 'இணைப்பு விவரங்கள்',
        helperSpecialties: 'உகவியாளர் சிறப்புகள்:',
        helperRating: 'உதவியாளர் மதிப்பீடு:',
        estProximity: 'மதிப்பிடப்பட்ட தூரம்:',
        kmAway: 'கிமீ தொலைவில்',
        cancelRequestBtn: 'கோரிக்கையை ரத்துசெய்',
        simulateAcceptBtn: '⚡ உதவியாளர் ஏற்பை உருவகப்படுத்தவும்',
        aiTitleSuggestions: 'தலைப்பு பரிந்துரைகள்:',
        aiClassifiedCategory: 'வகைப்படுத்தப்பட்ட பிரிவு:',
        aiSuggestedSkills: 'பரிந்துரைக்கப்பட்ட திறன்கள்:',
        aiPossibleSolutions: 'சாத்தியமான தீர்வுகள் (பொருந்தும் முன் பரிந்துரைகள்):',
        aiLoaderText: 'பகுப்பாய்வு செய்கிறது...',
        aiSuggestionsHeader: '🤖 ஃப்ளோசிண்ட் AI உதவி பரிந்துரைகள்',
        directChats: 'நேரடி அரட்டைகள்',
        filterUsers: 'பயனர்களை வடிகட்டவும்...',
        inboxStandbyTitle: 'ஃப்ளோசிண்ட் இன்பாக்ஸ் காத்திருப்பு',
        inboxStandbyDesc: 'உதவி வழங்கல்களை ஒருங்கிணைக்க ஒரு செயலில் உள்ள அரட்டையைத் தேர்ந்தெடுக்கவும்.',
        topMatchingHelpers: '🎯 சிறந்த பொருந்தும் உதவியாளர்கள்',
        radialExpandedHelpers: '📡 விரிவாக்கப்பட்ட பகுதி உதவியாளர்கள்',
        safeguardFooter: '🛡️ ஃப்ளோசிண்ட் AI பாதுகாப்பு தயார்: காப்பு முனைகள் மற்றும் இருப்பிட வகைப்படுத்திகள் தயார். பதிப்பு வ1.2.',
        workspaceMenu: 'பணிமனை மெனு',
        pinnedMessageLabel: '📌 பின்செய்யப்பட்ட செய்தி:',
        noMatchingMessages: 'பொருந்தும் செய்திகள் எதுவும் இல்லை.',
        noMessagesYet: 'இன்னும் செய்திகள் இல்லை. ஒருங்கிணைக்க செய்தி அனுப்பவும்.',
        youLabel: 'நீங்கள்',
        downloadLabel: 'பதிவிறக்கு',
        recordingVoiceNote: '🎤 குரல் குறிப்பு பதிவு செய்யப்படுகிறது...',
        attachFileTitle: 'கோப்பு / படத்தைச் சேர்க்கவும்',
        emojiDrawerTitle: 'ஈமோஜி தளம்',
        stopVoiceNote: 'குரல் குறிப்பை நிறுத்தி அனுப்பவும்',
        recordVoiceNote: 'குரல் குறிப்பை பதிவு செய்க',
        searchMessagesPlaceholder: 'செய்திகளைத் தேடு...',
        markRead: 'படித்ததாகக் குறிக்கவும்'
    }
};

export function UIProvider({ children }) {
    const [language, setLanguage] = useState(localStorage.getItem('flowzint_lang') || 'en');
    const [theme, setTheme] = useState(localStorage.getItem('flowzint_theme') || 'dark');

    useEffect(() => {
        localStorage.setItem('flowzint_lang', language);
    }, [language]);

    useEffect(() => {
        localStorage.setItem('flowzint_theme', theme);
        const root = document.documentElement;
        if (theme === 'light') {
            root.classList.add('light-theme');
        } else {
            root.classList.remove('light-theme');
        }
    }, [theme]);

    const t = (key) => {
        return translations[language]?.[key] || translations['en']?.[key] || key;
    };

    return (
        <UIContext.Provider value={{ language, setLanguage, theme, setTheme, t }}>
            {children}
        </UIContext.Provider>
    );
}

export function useUI() {
    return useContext(UIContext);
}
